export interface OceanDepthLayer {
  depth: number;
  label: string;
  zone: string;
  zoneDescription: string;
  tempMean: number;
  tempMin: number;
  tempMax: number;
  rmsePoseidon: number;
  rmseClimatology: number;
  rmseUNet: number;
  correlation: number;
  anomaly: number;
  isD20Isotherm?: boolean;
  isMLD?: boolean;
  thermalColors: {
    arabianSea: string;
    equator: string;
    bayOfBengal: string;
    contourStroke: string;
  };
}

export const OCEAN_DEPTH_LAYERS: OceanDepthLayer[] = [
  {
    depth: 0,
    label: "0 m (Surface)",
    zone: "Epipelagic",
    zoneDescription: "Satellite observation skin layer · Tropical Warm Pool",
    tempMean: 29.8,
    tempMin: 28.2,
    tempMax: 31.4,
    rmsePoseidon: 0.28,
    rmseClimatology: 0.82,
    rmseUNet: 0.44,
    correlation: 0.98,
    anomaly: +0.6,
    thermalColors: {
      arabianSea: "#e0633b",
      equator: "#f28b44",
      bayOfBengal: "#eb4d3d",
      contourStroke: "rgba(255,200,150,0.5)",
    },
  },
  {
    depth: 5,
    label: "5 m",
    zone: "Epipelagic",
    zoneDescription: "Upper mixed layer · High solar radiation penetration",
    tempMean: 29.6,
    tempMin: 28.0,
    tempMax: 31.1,
    rmsePoseidon: 0.29,
    rmseClimatology: 0.84,
    rmseUNet: 0.45,
    correlation: 0.98,
    anomaly: +0.5,
    thermalColors: {
      arabianSea: "#dd5f36",
      equator: "#ee843e",
      bayOfBengal: "#e74637",
      contourStroke: "rgba(255,190,140,0.5)",
    },
  },
  {
    depth: 10,
    label: "10 m",
    zone: "Epipelagic",
    zoneDescription: "Surface well-mixed column · High turbulent mixing",
    tempMean: 29.4,
    tempMin: 27.8,
    tempMax: 30.9,
    rmsePoseidon: 0.30,
    rmseClimatology: 0.85,
    rmseUNet: 0.46,
    correlation: 0.97,
    anomaly: +0.5,
    thermalColors: {
      arabianSea: "#d65a32",
      equator: "#e87e38",
      bayOfBengal: "#e24032",
      contourStroke: "rgba(255,185,130,0.45)",
    },
  },
  {
    depth: 20,
    label: "20 m",
    zone: "Mixed Layer Depth (MLD)",
    zoneDescription: "Mean summer mixed layer base · Wind-driven homogeneity",
    tempMean: 28.9,
    tempMin: 27.2,
    tempMax: 30.3,
    rmsePoseidon: 0.32,
    rmseClimatology: 0.89,
    rmseUNet: 0.49,
    correlation: 0.97,
    anomaly: +0.4,
    isMLD: true,
    thermalColors: {
      arabianSea: "#cb532d",
      equator: "#de7432",
      bayOfBengal: "#d8382c",
      contourStroke: "rgba(255,175,120,0.45)",
    },
  },
  {
    depth: 30,
    label: "30 m",
    zone: "Mixed Layer Base",
    zoneDescription: "Transition to upper thermocline · Pycnocline onset",
    tempMean: 28.1,
    tempMin: 26.4,
    tempMax: 29.5,
    rmsePoseidon: 0.35,
    rmseClimatology: 0.94,
    rmseUNet: 0.53,
    correlation: 0.96,
    anomaly: +0.3,
    thermalColors: {
      arabianSea: "#bd4f2e",
      equator: "#ce6832",
      bayOfBengal: "#c8352b",
      contourStroke: "rgba(255,160,110,0.45)",
    },
  },
  {
    depth: 50,
    label: "50 m",
    zone: "Upper Thermocline",
    zoneDescription: "Rapid vertical temperature gradient onset · Barrier layer cutoff",
    tempMean: 26.7,
    tempMin: 24.8,
    tempMax: 28.2,
    rmsePoseidon: 0.41,
    rmseClimatology: 1.08,
    rmseUNet: 0.60,
    correlation: 0.95,
    anomaly: +0.2,
    thermalColors: {
      arabianSea: "#9d4b39",
      equator: "#b45938",
      bayOfBengal: "#a73838",
      contourStroke: "rgba(230,140,120,0.45)",
    },
  },
  {
    depth: 75,
    label: "75 m",
    zone: "Core Thermocline",
    zoneDescription: "Intense vertical gradient (dT/dz peak) · Upwelling sensitive",
    tempMean: 24.2,
    tempMin: 22.0,
    tempMax: 26.1,
    rmsePoseidon: 0.49,
    rmseClimatology: 1.25,
    rmseUNet: 0.71,
    correlation: 0.93,
    anomaly: -0.1,
    thermalColors: {
      arabianSea: "#69555c",
      equator: "#815e61",
      bayOfBengal: "#734e5a",
      contourStroke: "rgba(180,140,160,0.45)",
    },
  },
  {
    depth: 100,
    label: "100 m",
    zone: "Thermocline / D20 Isotherm",
    zoneDescription: "D20 20°C isotherm indicator depth · Monsoon circulation proxy",
    tempMean: 21.4,
    tempMin: 19.1,
    tempMax: 23.5,
    rmsePoseidon: 0.52,
    rmseClimatology: 1.42,
    rmseUNet: 0.78,
    correlation: 0.91,
    anomaly: -0.3,
    isD20Isotherm: true,
    thermalColors: {
      arabianSea: "#386588",
      equator: "#48759c",
      bayOfBengal: "#355e82",
      contourStroke: "rgba(100,200,255,0.6)",
    },
  },
  {
    depth: 125,
    label: "125 m",
    zone: "Lower Thermocline",
    zoneDescription: "Sub-surface cooling · Internal wave & Kelvin wave propagation",
    tempMean: 18.6,
    tempMin: 16.5,
    tempMax: 20.8,
    rmsePoseidon: 0.48,
    rmseClimatology: 1.35,
    rmseUNet: 0.72,
    correlation: 0.92,
    anomaly: -0.4,
    thermalColors: {
      arabianSea: "#276295",
      equator: "#3271a7",
      bayOfBengal: "#245989",
      contourStroke: "rgba(80,180,240,0.5)",
    },
  },
  {
    depth: 150,
    label: "150 m",
    zone: "Thermocline Base",
    zoneDescription: "Sub-thermocline transition · Arabian Sea High Salinity Water (ASHSW)",
    tempMean: 16.2,
    tempMin: 14.3,
    tempMax: 18.2,
    rmsePoseidon: 0.42,
    rmseClimatology: 1.22,
    rmseUNet: 0.65,
    correlation: 0.93,
    anomaly: -0.3,
    thermalColors: {
      arabianSea: "#1c5b9e",
      equator: "#2468af",
      bayOfBengal: "#1a518e",
      contourStroke: "rgba(60,160,230,0.45)",
    },
  },
  {
    depth: 200,
    label: "200 m",
    zone: "Mesopelagic / Twilight Zone",
    zoneDescription: "Permanent thermocline base · Red Sea Water mass presence",
    tempMean: 13.8,
    tempMin: 12.0,
    tempMax: 15.6,
    rmsePoseidon: 0.36,
    rmseClimatology: 1.05,
    rmseUNet: 0.56,
    correlation: 0.94,
    anomaly: -0.2,
    thermalColors: {
      arabianSea: "#154f9a",
      equator: "#1c5ca9",
      bayOfBengal: "#134689",
      contourStroke: "rgba(50,140,220,0.4)",
    },
  },
  {
    depth: 300,
    label: "300 m",
    zone: "Mesopelagic",
    zoneDescription: "Subsurface layer · Persian Gulf Water signature",
    tempMean: 11.4,
    tempMin: 9.8,
    tempMax: 12.9,
    rmsePoseidon: 0.28,
    rmseClimatology: 0.85,
    rmseUNet: 0.44,
    correlation: 0.95,
    anomaly: -0.1,
    thermalColors: {
      arabianSea: "#124388",
      equator: "#184f98",
      bayOfBengal: "#103c7a",
      contourStroke: "rgba(40,120,200,0.4)",
    },
  },
  {
    depth: 500,
    label: "500 m",
    zone: "Deep Mesopelagic",
    zoneDescription: "Stable cold intermediate water · Oxygen minimum zone (OMZ)",
    tempMean: 8.6,
    tempMin: 7.2,
    tempMax: 9.9,
    rmsePoseidon: 0.22,
    rmseClimatology: 0.68,
    rmseUNet: 0.35,
    correlation: 0.96,
    anomaly: +0.0,
    thermalColors: {
      arabianSea: "#0e3474",
      equator: "#133f84",
      bayOfBengal: "#0c2e68",
      contourStroke: "rgba(35,100,180,0.35)",
    },
  },
  {
    depth: 700,
    label: "700 m",
    zone: "Bathypelagic Transition",
    zoneDescription: "Equatorial deep jet influence · High density stratification",
    tempMean: 6.9,
    tempMin: 5.8,
    tempMax: 8.0,
    rmsePoseidon: 0.18,
    rmseClimatology: 0.54,
    rmseUNet: 0.28,
    correlation: 0.97,
    anomaly: +0.1,
    thermalColors: {
      arabianSea: "#0a265d",
      equator: "#0e2f6d",
      bayOfBengal: "#092252",
      contourStroke: "rgba(30,85,160,0.35)",
    },
  },
  {
    depth: 1000,
    label: "1000 m (Abyss)",
    zone: "Bathypelagic / Deep Ocean",
    zoneDescription: "Deep North Indian Ocean abyss · Cold Antarctic Intermediate Water",
    tempMean: 5.2,
    tempMin: 4.4,
    tempMax: 6.1,
    rmsePoseidon: 0.15,
    rmseClimatology: 0.45,
    rmseUNet: 0.24,
    correlation: 0.98,
    anomaly: +0.0,
    thermalColors: {
      arabianSea: "#071c48",
      equator: "#0a2254",
      bayOfBengal: "#06183e",
      contourStroke: "rgba(25,70,140,0.3)",
    },
  },
];
